CREATE TABLE SupportAgents (
    AgentID NUMBER PRIMARY KEY,
    FirstName VARCHAR2(50) NOT NULL,
    LastName VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Phone VARCHAR2(20)
);

CREATE TABLE Tickets (
    TicketID NUMBER PRIMARY KEY,
    CustomerName VARCHAR2(200) NOT NULL,
    Subject VARCHAR2(200) NOT NULL,
    Description CLOB NOT NULL,
    CreatedDate DATE DEFAULT SYSTIMESTAMP NOT NULL,
    LastUpdatedDate DATE DEFAULT SYSTIMESTAMP NOT NULL,
    StatusID NUMBER NOT NULL,
    AssignedToAgentID NUMBER,
    FOREIGN KEY (AssignedToAgentID) REFERENCES SupportAgents(AgentID)
);

CREATE SEQUENCE AgentSeq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER AgentTrigger BEFORE INSERT ON SupportAgents FOR EACH ROW BEGIN SELECT AgentSeq.NEXTVAL INTO :NEW.AgentID FROM DUAL; END;

CREATE SEQUENCE TicketSeq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TicketTrigger BEFORE INSERT ON Tickets FOR EACH ROW BEGIN SELECT TicketSeq.NEXTVAL INTO :NEW.TicketID FROM DUAL; END;
exit;
