CREATE TABLE SUPPORTAGENTS (
    AgentID NUMBER PRIMARY KEY,
    FirstName VARCHAR2(50) NOT NULL,
    LastName VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Phone VARCHAR2(20)
);

CREATE TABLE TICKETS (
    TicketID NUMBER PRIMARY KEY,
    CustomerName VARCHAR2(200) NOT NULL,
    Subject VARCHAR2(200) NOT NULL,
    Description CLOB NOT NULL,
    CreatedDate DATE DEFAULT SYSTIMESTAMP NOT NULL,
    LastUpdatedDate DATE DEFAULT SYSTIMESTAMP NOT NULL,
    StatusID NUMBER NOT NULL,
    AssignedToAgentID NUMBER,
    FOREIGN KEY (AssignedToAgentID) REFERENCES SupportAgents(AgentID)
);

CREATE INDEX TICKETS_SUBJECT_IDX ON TICKETS(Subject) INDEXTYPE IS CTXSYS.CONTEXT;    
CREATE INDEX TICKETS_DESCRIPTION_IDX ON TICKETS(Description) INDEXTYPE IS CTXSYS.CONTEXT;   
-- EXEC CTX_DDL.SYNC_INDEX('TICKETS_SUBJECT_IDX');
-- EXEC CTX_DDL.SYNC_INDEX('TICKETS_DESCRIPTION_IDX');

exit;
