CREATE TABLE SupportAgents (
    AgentID NUMBER PRIMARY KEY,
    FirstName VARCHAR2(50) NOT NULL,
    LastName VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Phone VARCHAR2(20)
);

CREATE TABLE Tickets (
    TicketID NUMBER PRIMARY KEY,
    CustomerName VARCHAR2(200) NOT NULL,
    Subject VARCHAR2(200) NOT NULL,
    Description CLOB NOT NULL,
    CreatedDate DATE DEFAULT SYSTIMESTAMP NOT NULL,
    LastUpdatedDate DATE DEFAULT SYSTIMESTAMP NOT NULL,
    StatusID NUMBER NOT NULL,
    AssignedToAgentID NUMBER,
    FOREIGN KEY (AssignedToAgentID) REFERENCES SupportAgents(AgentID)
);

exit;
